all: how-we-slack your-first-few-weeks useful-things-to-know

how-we-slack:
	relaxed how-we-slack.pug --build-once

your-first-few-weeks:
	relaxed your-first-few-weeks.pug --build-once --locals '{"name": "Somebody", "role": "frontend-engineer"}'

useful-things-to-know:
	relaxed useful-things-to-know.pug --build-once

.PHONY: all how-we-slack your-first-few-weeks useful-things-to-know
