all: how-we-slack your-first-few-weeks

how-we-slack:
	relaxed how-we-slack.pug --build-once

your-first-few-weeks:
	relaxed your-first-few-weeks.pug --build-once --locals '{"name": "Somebody"}'

.PHONY: all how-we-slack your-first-few-weeks
